# Github Recommended Settings
markdown: kramdown
kramdown:
        math_engine: mathjax
# Blog Settings
lang: en
domain: inzouzouwetrust.github.io
theme: jekyll-theme-minimal
title: Zouzou blog
description: easy geekery 



